db.host=localhost
db.port=3306
db.name=vikas
db.user=root
db.password=Amma@7758
db.params=useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

admin.username=admin
admin.password=admin123
